### ISSUE TITLE
problems with using simple slopes function 

### ISSUE THREAD

**Issue by jrabino3** [jeff-hughes/reghelper#10] opened 2021-03-20 17:35 UTC
I am trying to calculate simple slopes involving a 3-way interaction (apoe4:time:sleep_eff_10). See below:
``
library(nlme)
m1  <-  lme(EF ~ sex_recoded + race_recoded + educ_year_centered + BMI_masterfile_centered + apoe4 + sleep_meds + CVD + CESD_withoutslp + baseline_age_masterfile_centered + baseline_age_masterfile_centered:time + time + sleep_eff_10c + time:apoe4 +  sleep_eff_10c:time + apoe4:sleep_eff_10c + apoe4:time:sleep_eff_10c, random = ~1|idno, 
            data = df2, method = "REML", na.action = na.omit)
summary(m1)
``

I am using the reghelper package to calculate the simple slopes (see code below).
``
simple_slopes(m1, levels=list(apoe4=c(0, 1, 'sstest'),
                              time=c(0, 1, 2, 'sstest'), 
                              sleep_eff_10c=c(0.02, -4.67, 1.81, 'sstest')))
``
I am getting the following error message and warning:
``
Error in summary(new_model)$tTable[dummy_names, ] : 
  subscript out of bounds
In addition: Warning message:
Using formula(x) is deprecated when x is a character vector of length > 1.
  Consider formula(paste(x, collapse = " ")) instead. 
``
I tried to shorten the variable names and do a basic 2-way interaction, but i am still getting the error message. Can you please help?

**Comment by jrabino3** [comment] 2021-03-20 17:37
I am using the most recent version of the reghelper package (1.0.2).

**Comment by jeff-hughes** [comment] 2021-03-21 23:56
Hi @jrabino3,
I'm attempting to try and replicate the issue on my end to figure out the problem, but haven't been able to. Based on the line that's giving the error, it's evidently having an issue with a variable set as a factor in your data. (I'm guessing either "time" or "apoe4"). Somehow it's getting confused about the names of the contrasts (i.e., the column names when you run `contrasts(var_name)`). I've tried a few different combinations and haven't been able to get the error message you get, however.

So a couple things to try in order to narrow it down:
1. If you just run `simple_slopes(m1)`, does it run successfully?
2. For the factor variables in your model, can you confirm that the variable levels you're listing (e.g., 0 and 1 for `apoe4`; 0, 1, and 2 for `time`) are correct? And are they what gets listed in the row and column headers of `contrasts(df2$apoe4)` and `contrasts(df2$time)`?

If neither of those help to diagnose the problem, it would be helpful if you could provide a short reproducible example -- a small dataset similar enough to your data/model that produces the same error. Like I said, I have attempted to create some simulated data to test it out, but haven't been able to produce the error you're showing. So having a reproducible example is the only way for me to help.

**Comment by jrabino3** [comment] 2021-03-22 00:52
Hi @jeff-hughes. Thank you so much for your prompt response. I have tried to run simple_slopes(m1) and that did not work. I also checked that the values for apoe and time do exist within the dataframe. I have sent you an email (to your gmail account) about a reproducible example.

**Comment by jeff-hughes** [comment] 2021-03-23 21:01
I've had a quick go with the data & script you provided. I still wasn't able to reproduce the exact error about the subscript being out of bounds; however, I did get the warning about the character vector with length > 1. With a bit of debugging, I realized the issue was that it wasn't properly handling when the model formula was split across multiple lines. I am absolutely shocked that issue hasn't come up before now!

At any rate, that is an easy fix, and I can push a new version to deal with it. However, I'm wondering whether fixing that will also fix the subscript error for you as well, or if we need to keep digging. Would you be able to try putting your model formula on one line, re-fit the model, and then run `simple_slopes(m1)` and see if it still gives you the `Error in summary(new_model)$tTable[dummy_names, ] : subscript out of bounds` message?

It would also be useful to know what version of R you're using, and what OS you're on. I use Linux, and while that typically shouldn't make a difference, I'm having trouble figuring out why I don't get the same error message when using the same data and code as you. Could be a difference in the version of R, or perhaps nlme. Could you run `sessionInfo()` (after loading the packages you're using for this analysis) and paste the output here?

**Comment by jrabino3** [comment] 2021-03-23 21:18
Hi Jeff,

Thanks so much for the prompt response! I tried putting the model on one line and I am still getting that error message (see below). I've attached my revised script as well for your viewing (which basically has the model on one line as you suggested).
[cid:b2f5ab09-19f3-40b7-83d9-8804b65e8055]

Here is the session info you requested:

[cid:37393978-aff9-476d-a1ff-edb5d451e30c]

I can potentially reach out to a friend who has a Linux machine to see if they get the same error message.
________________________________

**Comment by jeff-hughes** [comment] 2021-03-23 21:27
Looks like the email reply ate what you pasted in! You might need to edit from Github directly...

**Comment by jrabino3** [comment] 2021-03-23 21:37
Thanks so much for the prompt response! I tried putting the model on one line and I am still getting that error message (see below). 

![Error and warning messages](https://user-images.githubusercontent.com/52975652/112221858-55100780-8bfe-11eb-921c-da037fd74e93.jpg)

Here is the session info you requested:
![Session Info](https://user-images.githubusercontent.com/52975652/112221883-60633300-8bfe-11eb-8dcb-c8d2ff4c1ead.jpg)

**Comment by jrabino3** [comment] 2021-03-23 21:38
Yikes! I just added in the screenshots.
________________________________

**Comment by jeff-hughes** [comment] 2021-03-23 23:57
Thanks for that. I don't see anything particularly jumping out at me there. I'm on R v4.0.4 instead of v4.0.2. Using nlme v3.1-151 instead of v3.1-148. But the likelihood of those minor version differences leading to some sort of breaking change is unlikely.

I did realize what I could do is push the change I made to Github, which you could then install from there to test. You can do this relatively easily with the following code:
```
install.packages("devtools")
devtools::install_github("jeff-hughes/reghelper")
```

Literally the only change I've made since the last version release is the change I just pushed to correct the "formula on multiple lines" warning. (I realized, after asking you to test putting your formula on one line, that R ends up splitting it back up onto multiple lines anyway....bit of an odd behaviour there.) So if you run the above code to install the package from Github, then rerun your code, that should tell us for real this time whether that fixes both errors or just the one.

If that still doesn't work, then I'm not particularly sure what else to try. If you're willing to upgrade your version of R to v4.0.4, that would be one option, but I know there's always the slight possibility that could break some other code you are relying on, so I will leave that decision up to you. I can also try setting up a Docker container with the same package versions you're using and see what I get; but that will take additional time on my part so I might not be able to get to it right away. And maybe by that point, you're better off just calculating the simple slopes the hard way....

**Comment by jrabino3** [comment] 2021-03-24 03:13
Hi @jeff-hughes! Good news! So, I upgraded my version of R and the nlme package and I actually go it to work! My model did end up breaking with all the covariates in the newer version of nlme, but that's another story. 

I was wondering if you could possibly help me with interpreting the output (see screenshot). I am particularly confused about what the last 3 lines of the output (sstest) represent. My understanding of the first two lines of the output for simple_slopes(m1) is that among folks who have apoe4 = 0, time doesn't affect the level of the outcome (EF) (or rather the affect of time on EF is not significant among folks who have apoe4 = 0. Same thing for apoe = 1.
<img width="705" alt="Screen Shot 2021-03-23 at 11 08 11 PM" src="https://user-images.githubusercontent.com/52975652/112248697-c070ce00-8c2c-11eb-903a-fcdee6314864.png">

You are a life savor!!!

**Comment by jeff-hughes** [comment] 2021-03-24 13:05
Oh, that's great to hear the update worked! I wouldn't have expected it...

At any rate, I see you've also emailed me separately about interpreting the output, so I'm going to close this issue and we can continue that discussion via email instead.

**Closed as completed by jeff-hughes** 2021-03-24 13:05 UTC
